name: Build


on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js env
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Hexo environment
      run: pnpm install

    - name: Hexo build site
      run: npx hexo generate --force

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
